### ISSUE TITLE
Please rename your fork

### ISSUE THREAD

**Issue by ahcm** [soedinglab/ffindex_soedinglab#1]
Hi,

please either use the offical github:
https://github.com/ahcm/ffindex
or rename your fork.

Cheers
Andy

**Comment by soeding** [comment]
Hi Andy,

no problem, we will rename our fork with the next release, due in weeks to a few months. 

Best,
Johannes

**Comment by ahcm** [comment]
Thanks, Johannes.

**Comment by meiermark** [comment]
The renaming was done.

Cheers,
Markus
